version: "3.7"
services:
  photobox-php:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: ./services/php/Dockerfile
    container_name: photobox-php
    restart: unless-stopped
    working_dir: /var/www/${APP_FOLDER}
    volumes:
      - /var/www/${APP_FOLDER}:/var/www/${APP_FOLDER}
      - ./services/php/usr/local/etc/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - photobox-network

  photobox-nginx:
    image: nginx:alpine
    container_name: photobox-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/www/${APP_FOLDER}:/var/www/${APP_FOLDER}
      - ./services/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - photobox-network

  photobox-postgresql:
    image: postgres:latest
    container_name: photobox-postgresql
    environment:
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: photobox
    ports:
      - "5432:5432"
    volumes:
      - photobox-postgresql-dbdata:/var/lib/postgresql/data
    networks:
      - photobox-network

networks:
  photobox-network:
    driver: bridge
volumes:
  photobox-postgresql-dbdata:
    driver: local
